version: 0.0
os: linux
files:
  - source: /src
    destination: /home/ec2-user/shusurvey
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_application
      timeout: 300
      runas: root